server.port=8000

# Instagram Configuration
instagram.verify.token=plugio_automation_2026
#instagram.access.token=EAHq1IZAwSeZCsBRcb9aCWFQquKoME23rfJtu6NXSnNHFWMPafHsjzCoM2vK5nViIF46pePmQo1ZAynkQiayVRJhQGyWwNlbeZAo82aA9YkUdYyqrKwKf41ZBN8J9iR1nZAx7ZAI8D5r7ZBZCkCjO8qd6YaaZCkjTW8mY3cvtYZAAi8S5Dh04mGiYYm1v1NXFP9mhyxCefEQnd54X4mfeTWUi4bKR9FEqq8IsnlDX1ugHkoZD
instagram.access.token=EAHq1IZAwSeZCsBRdZC3YqW6lZANjsOZACr5ZCjJD40omRUAza5O0MIbvQCMMjnLHzqKkmTPgjC7cRfatDSdUg4PAmI0ZB79fSIYuSQUHZA3aipo7BfiLZBwokP6vFUJ8zRFeXAKLAJaEpUgfLBQ7kQZBdZA3iKAsUiWtXTtiZAMTJMTwzC9ZBWH8DGrPwq8s1mE1PBTTunexE0s4fa2bdct8oUA9WLX7g90UkVy5HRZBmvBBvdhqOPNmsxEB8sQ3m7qunJNLhlOzmHXSTMYwCEMAYbIi00IZACh
instagram.business.account.id=17841473655798747
instagram.page.id=717642938108173

# Logging
logging.level.app.plugio.automation=DEBUG
logging.level.org.springframework.web=INFO

spring.main.banner-mode=off

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/automation_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Task Scheduling
spring.task.scheduling.pool.size=2
